common: &common
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: results_app_dev
  pool: 50
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *common

staging:
  <<: *common

test:
  <<: *common
  database: results_app_test

production:
  <<: *common
  statement_limit: 500